version: "3.9"

services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app

  db:
    image: postgres:14.0-alpine
    volumes:
      - ./postgres:/var/lib/postgresql/data